global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'exporter-metrics'

scrape_configs:
- job_name: 'HostsMetrics'
  dns_sd_configs:
  - names:
    - node-exporter
    refresh_interval: 15s
    type: A
    port: 9100

- job_name: 'ContainerMetrics'
  dns_sd_configs:
  - names:
    - ranch-eye
    refresh_interval: 15s
    type: A
    port: 9104

- job_name: 'rancher-api'
  target_groups:
    - targets:
        - 'prometheus-rancher-exporter:9010'

- job_name: 'pixsmash-api'
  dns_sd_configs:
  - names:
    - api.pixsmash
    refresh_interval: 15s
    type: A
    port: 5020

- job_name: 'expire-worker'
  dns_sd_configs:
  - names:
    - expireWorker.pixsmash
    refresh_interval: 15s
    type: A
    port: 5021

- job_name: 'random-server'
  dns_sd_configs:
  - names:
    - randomServer.pixsmash
    refresh_interval: 15s
    type: A
    port: 5022
